server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/carepoint?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    type-aliases-package: com.aws.carepoint.domain

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
