server:
  port: 8081

spring:
  config:
    import: classpath:application-DB.yml  # DB 설정을 application-DB.yml에서 불러옴
  profiles:
<<<<<<< HEAD
    active: local  # 기본 환경을 local로 설정 (선택 사항)
=======
    active: local  # 기본 환경을 local로 설정 (선택 사항)



>>>>>>> df4d74ac3d213e01b1040c5f42d112331dd328d1
